insert into codes (code, type, variable, screen, amount, value, active) values ('54629679', 'join', 'VFY', NULL, NULL, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('3og6aexi5V', 'cmoney', 'code9', NULL, 1500, '{"id": 3}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('5oeq6AVMYz', 'item', 'code6', 'item_15_100', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('5xiGriF40a', 'item', 'code11', 'item_ginseng1', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('6gP5xCfBNm', 'item', 'code4', 'item_viprin', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('BFhaRuLSjb', 'money', 'code12', NULL, 500, '{"id": 1}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('C8DeKZUSrv', 'item', 'code18', 'item_flower_scraps', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('DVcsOmCeRb', 'item', 'code16', 'item_bagpack', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('EwYg9btjtD', 'money', 'code3', NULL, 1500, '{"id": 1}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('GnqVcm9A46', 'cmoney', 'code8', NULL, 1000, '{"id": 3}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('LQznls4MoM', 'money', 'code1', NULL, 1000, '{"id": 1}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('MasterGameH', 'money', 'code17', NULL, 500, '{"id": 1}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('MbE8RA184n', 'item', 'code10', 'item_fitnesscardvip', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('SOkja22j4g', 'item', 'code22', 'item_socks_atlas', 1, '{" active": true}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('SS5uYg50qz', 'background', 'persistent.codeENDDEMO010', 'item_demo', NULL, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('SuperCowboiYouTube', 'money', 'code14', NULL, 1000, '{"id": 1}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('a9Kjfqq2vz', 'cmoney', 'code15', NULL, 500, '{"id": 3}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('dsZxZT1U9a', 'background', 'persistent.coderinb', 'item_srin', NULL, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('hAAlni04ba', 'item', 'code19', 'item_bunnygirl', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('hgiqnzddlg', 'item', 'code20', 'item_hat_atlas', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('kZvABtSyim', 'money', 'code2', NULL, 500, '{"id": 1}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('maOi7gaMnp', 'item', 'code5', 'item_soup', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('qHpJeG1vJ3', 'setvariable', 'persistent.specialmainmenu', NULL, NULL, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('resetdemo', 'setbg', 'codeENDDEMO010', NULL, NULL, '{"value": false}'::jsonb, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('s7siNHfbyN', 'item', 'code17', 'item_The_Von_Draven_Signet_Ring', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('set100', 'setm', NULL, NULL, 0, NULL, false) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('setbeef', 'setam', NULL, 'item_energydrink1', 0, NULL, false) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('setd', 'setdf', 'code1', NULL, NULL, '{"value": false}'::jsonb, false) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('setdfvip', 'setdf', 'code6', NULL, NULL, '{"value": false}'::jsonb, false) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('wlhhab9Hua', 'item', 'code21', 'item_gloves_atlas', 1, NULL, true) on conflict (code) do nothing;
insert into codes (code, type, variable, screen, amount, value, active) values ('xvbdihwS5d', 'cmoney', 'code7', NULL, 500, '{"id": 3}'::jsonb, true) on conflict (code) do nothing;
